ALTER TABLE "Opportunity"
  ADD COLUMN IF NOT EXISTS "projectType" TEXT NOT NULL DEFAULT 'SINGLE',
  ADD COLUMN IF NOT EXISTS "projectMonths" INTEGER;

ALTER TABLE "Commission"
  ADD COLUMN IF NOT EXISTS "calculationBase" DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS "projectType" TEXT NOT NULL DEFAULT 'SINGLE',
  ADD COLUMN IF NOT EXISTS "projectMonths" INTEGER;
